### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by oooseun** [ugoArangino/MJPEG-Framework#1]
Hi, Can you include a simple (or detailed) how-to in the ReadMe.MD ? i'm lost.
I want to use this as a simple webcam viewer inside an application, and i have no idea how to even begin with your code. Thanks

**Comment by ugoArangino** [comment]
I have added an example to the [README.md](https://raw.githubusercontent.com/ugoArangino/MJPEG-Framework/master/README.md) and created an example project

**Comment by oooseun** [comment]
Thanks!
